### ISSUE TITLE
the container fails  when built using the container file given in the example

### ISSUE THREAD

**Issue by mpaulgreen** [rh-aiservices-bu/llm-on-openshift#13]
Please refer to the file - https://github.com/rh-aiservices-bu/llm-on-openshift/blob/main/examples/ui/gradio/gradio-hftgi-rag-redis/Containerfile. When you try to run the container it fails with an error ```python: can't open file '/opt/app-root/src/app.py': [Errno 13] Permission denied```. I was using my own app.py. @guimou FYI

**Comment by guimou** [comment]
Interesting... I swear the prebuilt images are directly from the code in
the repo once it has been pushed.
Do you have the container image itself somewhere, like on Quay so I can
have a look?

**Comment by mpaulgreen** [comment]
@guimou  You can find the image in ```quay.io/mpaulgreen/gradioapp:latest```. The code is in this repository ```https://github.com/mpaulgreen/gradiocontainer.git```.  I am pretty much using the Container file from this repo.

**Comment by guimou** [comment]
Well, technically it's not an issue with this repo because it's not the same Containerfile, not the same app.py file, and not the same requirements.txt :smile: . But I had a look at it anyway.
This is the content of your image once built (direct from the Quay repo):
```
(app-root) (app-root) ls -la
total 16
drwxrwxr-x 3 default root 4096 Oct 21 12:54 .
drwxrwxr-x 8 default root 4096 Oct 21 12:52 ..
-rw------- 1 root    root  964 Oct 21 12:51 app.py
drwxrwxr-x 3 default root 4096 Oct 17 12:54 .pki
```
So obviously, with a root owner and permissions set as 600, the file cannot even be read once run in OpenShift with a default account.

When a file is copied in a container image with the COPY command, it comes by default with the same permission set as the original file. Also, a COPY command is always executed by default as root owner.
So if in your original repo (or where you build the image from), you file is set with permissions 600, you end up in the situation described above.
On my system, I have the default permissions for newly created files set at 644 (pretty standard config). So I end up in my builds with:
```
-rw-r--r-- 1 root    root  950 Oct 22 12:47 app.py
```
Still root owned, but accessible by anyone, including the default account on OpenShift.

So from there you have two options:
- Check your original permissions on the `app.py` file, to have at least 644.
- Copy the file in the container but change the ownership on the fly:
`COPY --chown=1001:0 app.py ./`
(for Openshift-compatible containers, user has to be default (1001), and group 0).

That said I will surely modify my Containerfile to force the ownership, that may prevent others facing the same issue. This is [what I usually do](https://github.com/opendatahub-io-contrib/workbench-images/blob/c57d71037b0600d3fa8b65e32bc8b1511123f20b/snippets/ides/1-jupyter/jupyter.snippet#L10) for more advanced situations, I just did not think about it for this more simple app use case.

**Comment by mpaulgreen** [comment]
Thanks @guimou for looking into this. I am pretty sure I verified from the ui/examples and it was also not running. It will be a good idea to include ```COPY --chown=1001:0 app.py ./``` in all the example Containerfile.

**Comment by mpaulgreen** [comment]
This issue is closed with above mentioned resolution.
